import 'package:flutter_test/flutter_test.dart';
import 'package:metmusic/player/stream_proxy.dart';

void main() {
  group('parseRangeHeader', () {
    test('parses the open-ended range ExoPlayer opens with', () {
      // This exact header is what the platform player sends first, and what
      // googlevideo rejects with 403.
      final range = parseRangeHeader('bytes=0-');
      expect(range, isNotNull);
      expect(range!.start, 0);
      expect(range.end, isNull);
    });

    test('parses a bounded range', () {
      final range = parseRangeHeader('bytes=1000-2000');
      expect(range!.start, 1000);
      expect(range.end, 2000);
    });

    test('tolerates whitespace and casing', () {
      final range = parseRangeHeader('  BYTES = 0 - 524287 ');
      expect(range!.start, 0);
      expect(range.end, 524287);
    });

    test('returns null when no range is requested', () {
      expect(parseRangeHeader(null), isNull);
    });

    test('returns null for unsupported forms', () {
      // Suffix and multi-range forms are not generated by the player.
      expect(parseRangeHeader('bytes=-500'), isNull);
      expect(parseRangeHeader('bytes=0-100,200-300'), isNull);
      expect(parseRangeHeader('nonsense'), isNull);
    });
  });

  group('StreamProxy chunk size', () {
    test('stays within the range the CDN serves', () {
      // Measured: ranges beyond roughly 1 MiB are refused with 403.
      expect(StreamProxy.chunkSize, lessThanOrEqualTo(1024 * 1024));
    });
  });
}