import 'dart:async';
import 'dart:io';
import 'dart:math' as math;

/// Rewrites an incoming `Range` header into byte offsets.
///
/// Returns `null` when the header is absent or unparseable, meaning the caller
/// should serve the whole resource.
({int start, int? end})? parseRangeHeader(String? header) {
  if (header == null) {
    return null;
  }
  final match = RegExp(
    r'^\s*bytes\s*=\s*(\d+)\s*-\s*(\d*)\s*$',
    caseSensitive: false,
  ).firstMatch(header);
  if (match == null) {
    // Suffix and multi-range forms are not generated by the player.
    return null;
  }
  final start = int.tryParse(match.group(1) ?? '');
  if (start == null) {
    return null;
  }
  final rawEnd = match.group(2) ?? '';
  return (start: start, end: rawEnd.isEmpty ? null : int.tryParse(rawEnd));
}

/// A loopback HTTP server that fronts one resolved InnerTube stream.
///
/// ExoPlayer opens with an open-ended range (`bytes=0-`), which googlevideo
/// answers with 403; only bounded ranges are served. This proxy accepts
/// whatever the player asks for and satisfies it with bounded upstream reads,
/// while keeping the identity-bound headers and the signed URL inside the app
/// instead of handing them to the platform player.
final class StreamProxy {
  StreamProxy._(
    this._server,
    this._videoId,
    this._upstream,
    this._headers,
    this._totalLength,
    this.onUpstreamStalled,
  );

  /// Upstream range size. Bounded reads are required; this stays well under the
  /// range the CDN serves.
  static const int chunkSize = 256 * 1024;

  final HttpServer _server;
  final String _videoId;
  final HttpClient _client = HttpClient();

  final Uri _upstream;
  final Map<String, String> _headers;
  final int? _totalLength;
  final void Function()? onUpstreamStalled;
  bool _closed = false;

  static Future<StreamProxy> start({
    required String videoId,
    required Uri uri,
    required Map<String, String> headers,
    int? totalLength,
    void Function()? onUpstreamStalled,
  }) async {
    final server = await HttpServer.bind(
      InternetAddress.loopbackIPv4,
      0,
      shared: false,
    );
    final proxy = StreamProxy._(
      server,
      videoId,
      uri,
      Map<String, String>.unmodifiable(headers),
      totalLength,
      onUpstreamStalled,
    );
    server.listen(proxy._handle, onError: (Object _) {});
    return proxy;
  }

  /// Loopback URL to hand to the player.
  Uri get uri => Uri.parse('http://127.0.0.1:${_server.port}/stream');

  /// Video currently served, for diagnostics.
  String get videoId => _videoId;

  Future<void> _handle(HttpRequest request) async {
    if (_closed) {
      request.response.statusCode = HttpStatus.serviceUnavailable;
      await request.response.close();
      return;
    }

    try {
      final total = await _resolveTotalLength();
      if (total == null || total <= 0) {
        request.response.statusCode = HttpStatus.badGateway;
        await request.response.close();
        return;
      }

      final range = parseRangeHeader(
        request.headers.value(HttpHeaders.rangeHeader),
      );
      final start = range?.start ?? 0;
      final end = math.min(range?.end ?? total - 1, total - 1);

      if (start >= total || start > end) {
        request.response.statusCode = HttpStatus.requestedRangeNotSatisfiable;
        request.response.headers.set(
          HttpHeaders.contentRangeHeader,
          'bytes */$total',
        );
        await request.response.close();
        return;
      }

      final isPartial = range != null;
      request.response
        ..statusCode = isPartial
            ? HttpStatus.partialContent
            : HttpStatus.ok
        ..headers.set(HttpHeaders.acceptRangesHeader, 'bytes')
        // Declared before the first byte is written, because the headers are
        // flushed as soon as the body starts. ExoPlayer derives the track
        // duration from this and refuses to seek without it.
        ..headers.contentLength = end - start + 1;

      if (isPartial) {
        request.response.headers.set(
          HttpHeaders.contentRangeHeader,
          'bytes $start-$end/$total',
        );
      }

      // A short delivery is reported so the player can re-resolve, but the
      // declared length stands: a truncated transfer is what makes ExoPlayer
      // retry the range, which is what we want.
      await _pipe(request, start, end);
    } on Object {
      // The player disconnected (seek or skip); nothing to recover.
    } finally {
      try {
        await request.response.close();
      } on Object {
        // Already closed.
      }
    }
  }

  /// Streams `[start, end]` using bounded upstream requests.
///
/// Returns how many bytes were actually written, which can be fewer than
/// requested when upstream refuses a deep range.
  Future<int> _pipe(HttpRequest request, int start, int end) async {
    final response = request.response;
    var position = start;
    while (position <= end) {
      final chunkEnd = math.min(position + chunkSize - 1, end);
      final bytes = await _fetch(position, chunkEnd);
      if (bytes == null || bytes.isEmpty) {
        // A refusal partway through means the CDN stopped serving this URL at
        // depth, not that the track ended. The player swaps in a fresh source
        // so playback continues instead of stopping at the ceiling.
        if (position > start && position < end) {
          onUpstreamStalled?.call();
        }
        // Nothing more will arrive; close early rather than hang the player.
        return position - start;
      }
      response.add(bytes);
      position += bytes.length;
    }
    return position - start;
  }

  /// One bounded ranged request against googlevideo.
  Future<List<int>?> _fetch(int start, int end) async {
    if (_closed) {
      return null;
    }
    try {
      final request = await _client.getUrl(_upstream);
      request.headers.set(HttpHeaders.rangeHeader, 'bytes=$start-$end');
      // Required: the URL is bound to the identity that produced it.
      _headers.forEach(request.headers.set);

      final response = await request.close();
      if (response.statusCode != HttpStatus.partialContent &&
          response.statusCode != HttpStatus.ok) {
        return null;
      }

      final builder = <int>[];
      await for (final chunk in response) {
        builder.addAll(chunk);
      }
      return builder;
    } on Object {
      return null;
    }
  }

  /// Resolves the full content length, probing once when the catalog omits it.
  Future<int?> _resolveTotalLength() async {
    final known = _totalLength;
    if (known != null && known > 0) {
      return known;
    }

    try {
      final request = await _client.getUrl(_upstream);
      request.headers.set(HttpHeaders.rangeHeader, 'bytes=0-0');
      _headers.forEach(request.headers.set);

      final response = await request.close();
      final contentRange = response.headers.value(
        HttpHeaders.contentRangeHeader,
      );
      await response.drain<void>();
      if (contentRange == null) {
        return null;
      }
      final total = RegExp(r'/(\d+)\s*$').firstMatch(contentRange);
      return total == null ? null : int.tryParse(total.group(1)!);
    } on Object {
      return null;
    }
  }

  Future<void> close() async {
    if (_closed) {
      return;
    }
    _closed = true;
    await _server.close(force: true);
    _client.close(force: true);
  }
}